-- MySQL Script generated by MySQL Workbench
-- 06/27/14 11:28:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rest` ;

-- -----------------------------------------------------
-- Table `rest`.`sd_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `visibility` TINYINT NULL DEFAULT 0,
  `social_link` TEXT NULL,
  `social_link_signup` TEXT NULL,
  `status` TINYINT NULL DEFAULT 0,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `access_token` VARCHAR(45) NOT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickname_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_galleries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_galleries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `owner` INT NULL,
  `visibility` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 0,
  `created_at` INT NOT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `owner` INT NULL,
  `visibility` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 0,
  `created_at` INT NOT NULL,
  `updated_at` INT NULL,
  `sd_galleries_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_galleries_id`),
  INDEX `fk_sd_images_sd_galleries1_idx` (`sd_galleries_id` ASC),
  CONSTRAINT `fk_sd_images_sd_galleries1`
    FOREIGN KEY (`sd_galleries_id`)
    REFERENCES `rest`.`sd_galleries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `owner` INT NULL,
  `visibility` TINYINT NULL DEFAULT 0,
  `status` TINYINT NULL DEFAULT 0,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `sd_galleries_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_galleries_id`),
  INDEX `fk_sd_countries_sd_galleries1_idx` (`sd_galleries_id` ASC),
  CONSTRAINT `fk_sd_countries_sd_galleries1`
    FOREIGN KEY (`sd_galleries_id`)
    REFERENCES `rest`.`sd_galleries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `short_info` VARCHAR(255) NULL,
  `owner` INT NULL,
  `visibility` TINYINT NULL DEFAULT 0,
  `status` TINYINT NULL DEFAULT 0,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `sd_galleries_id` INT NOT NULL,
  `sd_countries_id` INT NOT NULL,
  `contact` TEXT NULL,
  PRIMARY KEY (`id`, `sd_galleries_id`, `sd_countries_id`),
  INDEX `fk_sd_companies_sd_galleries1_idx` (`sd_galleries_id` ASC),
  INDEX `fk_sd_companies_sd_countries1_idx` (`sd_countries_id` ASC),
  CONSTRAINT `fk_sd_companies_sd_galleries1`
    FOREIGN KEY (`sd_galleries_id`)
    REFERENCES `rest`.`sd_galleries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_companies_sd_countries1`
    FOREIGN KEY (`sd_countries_id`)
    REFERENCES `rest`.`sd_countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `owner` INT NULL,
  `visibility` TINYINT NULL DEFAULT 0,
  `status` TINYINT NULL DEFAULT 0,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `sd_galleries_id` INT NOT NULL,
  `sd_companies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_galleries_id`, `sd_companies_id`),
  INDEX `fk_sd_products_sd_galleries1_idx` (`sd_galleries_id` ASC),
  INDEX `fk_sd_products_sd_companies1_idx` (`sd_companies_id` ASC),
  CONSTRAINT `fk_sd_products_sd_galleries1`
    FOREIGN KEY (`sd_galleries_id`)
    REFERENCES `rest`.`sd_galleries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_products_sd_companies1`
    FOREIGN KEY (`sd_companies_id`)
    REFERENCES `rest`.`sd_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_boycotts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_boycotts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `target_type` VARCHAR(45) NULL,
  `target_id` INT NULL,
  `description` TEXT NULL,
  `demand` TEXT NULL,
  `taxonomy_tag` TEXT NULL,
  `owner` INT NULL,
  `visibility` TINYINT NULL DEFAULT 0,
  `status` TINYINT NULL DEFAULT 0,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `sd_companies_id` INT NOT NULL,
  `sd_countries_id` INT NOT NULL,
  `sd_products_id` INT NOT NULL,
  `sd_users_id` INT NOT NULL,
  `notification_time` INT NULL,
  `notification_number` INT NULL,
  PRIMARY KEY (`id`, `sd_companies_id`, `sd_countries_id`, `sd_products_id`, `sd_users_id`),
  INDEX `fk_sd_boycotts_sd_companies1_idx` (`sd_companies_id` ASC),
  INDEX `fk_sd_boycotts_sd_countries1_idx` (`sd_countries_id` ASC),
  INDEX `fk_sd_boycotts_sd_products1_idx` (`sd_products_id` ASC),
  INDEX `fk_sd_boycotts_sd_users1_idx` (`sd_users_id` ASC),
  CONSTRAINT `fk_sd_boycotts_sd_companies1`
    FOREIGN KEY (`sd_companies_id`)
    REFERENCES `rest`.`sd_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_boycotts_sd_countries1`
    FOREIGN KEY (`sd_countries_id`)
    REFERENCES `rest`.`sd_countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_boycotts_sd_products1`
    FOREIGN KEY (`sd_products_id`)
    REFERENCES `rest`.`sd_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_boycotts_sd_users1`
    FOREIGN KEY (`sd_users_id`)
    REFERENCES `rest`.`sd_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `sd_users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_users_id`),
  INDEX `fk_sd_tags_sd_users1_idx` (`sd_users_id` ASC),
  CONSTRAINT `fk_sd_tags_sd_users1`
    FOREIGN KEY (`sd_users_id`)
    REFERENCES `rest`.`sd_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_userprofiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_userprofiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sd_users_id` INT NOT NULL,
  `birthday` DATETIME NULL,
  `profile_picture` VARCHAR(255) NULL,
  `bio` TEXT NULL,
  `total` INT NULL,
  `name` VARCHAR(100) NULL,
  `surname` VARCHAR(100) NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`, `sd_users_id`),
  INDEX `fk_sd_userprofiles_sd_users1_idx` (`sd_users_id` ASC),
  CONSTRAINT `fk_sd_userprofiles_sd_users1`
    FOREIGN KEY (`sd_users_id`)
    REFERENCES `rest`.`sd_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_badges_and_challenges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_badges_and_challenges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `text` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `points` INT NULL,
  `string_id` VARCHAR(255) NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `type` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `string_id_UNIQUE` (`string_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_gamifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_gamifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `f_id` INT NULL,
  `points` INT NULL,
  `reason` TEXT NULL,
  `target` VARCHAR(45) NULL,
  `sd_userprofiles_id` INT NOT NULL,
  `created_at` INT NULL,
  `updated-at` INT NULL,
  `sd_badges_and_challenges_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_userprofiles_id`, `sd_badges_and_challenges_id`),
  INDEX `fk_sd_gamifications_sd_userprofiles1_idx` (`sd_userprofiles_id` ASC),
  INDEX `fk_sd_gamifications_sd_badges_and_challenges1_idx` (`sd_badges_and_challenges_id` ASC),
  CONSTRAINT `fk_sd_gamifications_sd_userprofiles1`
    FOREIGN KEY (`sd_userprofiles_id`)
    REFERENCES `rest`.`sd_userprofiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_gamifications_sd_badges_and_challenges1`
    FOREIGN KEY (`sd_badges_and_challenges_id`)
    REFERENCES `rest`.`sd_badges_and_challenges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_challenges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_challenges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `text` TEXT NULL,
  `image` VARCHAR(255) NULL,
  `points` INT NULL,
  `string_id` VARCHAR(255) NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `string_id_UNIQUE` (`string_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `text` TEXT NULL,
  `trigger` VARCHAR(255) NULL,
  `sender` INT NULL,
  `status` TINYINT NULL DEFAULT 0,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `trigger_UNIQUE` (`trigger` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `taxonomy_tag` VARCHAR(45) NULL,
  `is_published` TINYINT NULL DEFAULT 0,
  `published_date` DATETIME NULL,
  `owener` INT NULL,
  `visibility` TINYINT NULL DEFAULT 0,
  `status` TINYINT NULL DEFAULT 0,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `content` TEXT NULL,
  `sd_galleries_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_galleries_id`),
  INDEX `fk_sd_news_sd_galleries1_idx` (`sd_galleries_id` ASC),
  CONSTRAINT `fk_sd_news_sd_galleries1`
    FOREIGN KEY (`sd_galleries_id`)
    REFERENCES `rest`.`sd_galleries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_tags_has_sd_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_tags_has_sd_news` (
  `sd_tags_id` INT NOT NULL,
  `sd_news_id` INT NOT NULL,
  PRIMARY KEY (`sd_tags_id`, `sd_news_id`),
  INDEX `fk_sd_tags_has_sd_news_sd_news1_idx` (`sd_news_id` ASC),
  INDEX `fk_sd_tags_has_sd_news_sd_tags_idx` (`sd_tags_id` ASC),
  CONSTRAINT `fk_sd_tags_has_sd_news_sd_tags`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_tags_has_sd_news_sd_news1`
    FOREIGN KEY (`sd_news_id`)
    REFERENCES `rest`.`sd_news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_boycott_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_boycott_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NULL,
  `sd_boycotts_id` INT NOT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`, `sd_boycotts_id`),
  INDEX `fk_sd_boycott_images_sd_boycotts1_idx` (`sd_boycotts_id` ASC),
  CONSTRAINT `fk_sd_boycott_images_sd_boycotts1`
    FOREIGN KEY (`sd_boycotts_id`)
    REFERENCES `rest`.`sd_boycotts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_boycott_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_boycott_links` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(255) NULL,
  `sd_boycotts_id` INT NOT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`, `sd_boycotts_id`),
  INDEX `fk_sd_boycott_links_sd_boycotts1_idx` (`sd_boycotts_id` ASC),
  CONSTRAINT `fk_sd_boycott_links_sd_boycotts1`
    FOREIGN KEY (`sd_boycotts_id`)
    REFERENCES `rest`.`sd_boycotts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_companies_active_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_companies_active_country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sd_companies_id` INT NOT NULL,
  `sd_countries_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_companies_id`, `sd_countries_id`),
  INDEX `fk_sd_companies_active_country_sd_companies1_idx` (`sd_companies_id` ASC),
  INDEX `fk_sd_companies_active_country_sd_countries1_idx` (`sd_countries_id` ASC),
  CONSTRAINT `fk_sd_companies_active_country_sd_companies1`
    FOREIGN KEY (`sd_companies_id`)
    REFERENCES `rest`.`sd_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_companies_active_country_sd_countries1`
    FOREIGN KEY (`sd_countries_id`)
    REFERENCES `rest`.`sd_countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_news_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_news_has_sd_tags` (
  `sd_news_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_news_id`, `sd_tags_id`),
  INDEX `fk_sd_news_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_news_has_sd_tags_sd_news1_idx` (`sd_news_id` ASC),
  CONSTRAINT `fk_sd_news_has_sd_tags_sd_news1`
    FOREIGN KEY (`sd_news_id`)
    REFERENCES `rest`.`sd_news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_news_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_boycotts_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_boycotts_has_sd_tags` (
  `sd_boycotts_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_boycotts_id`, `sd_tags_id`),
  INDEX `fk_sd_boycotts_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_boycotts_has_sd_tags_sd_boycotts1_idx` (`sd_boycotts_id` ASC),
  CONSTRAINT `fk_sd_boycotts_has_sd_tags_sd_boycotts1`
    FOREIGN KEY (`sd_boycotts_id`)
    REFERENCES `rest`.`sd_boycotts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_boycotts_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_images_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_images_has_sd_tags` (
  `sd_images_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_images_id`, `sd_tags_id`),
  INDEX `fk_sd_images_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_images_has_sd_tags_sd_images1_idx` (`sd_images_id` ASC),
  CONSTRAINT `fk_sd_images_has_sd_tags_sd_images1`
    FOREIGN KEY (`sd_images_id`)
    REFERENCES `rest`.`sd_images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_images_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_galleries_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_galleries_has_sd_tags` (
  `sd_galleries_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_galleries_id`, `sd_tags_id`),
  INDEX `fk_sd_galleries_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_galleries_has_sd_tags_sd_galleries1_idx` (`sd_galleries_id` ASC),
  CONSTRAINT `fk_sd_galleries_has_sd_tags_sd_galleries1`
    FOREIGN KEY (`sd_galleries_id`)
    REFERENCES `rest`.`sd_galleries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_galleries_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `type` VARCHAR(45) NULL,
  `target_type` VARCHAR(45) NULL,
  `sd_users_id` INT NOT NULL,
  `f_id` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sd_comments_sd_users1_idx` (`sd_users_id` ASC),
  CONSTRAINT `fk_sd_comments_sd_users1`
    FOREIGN KEY (`sd_users_id`)
    REFERENCES `rest`.`sd_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `target_type` VARCHAR(45) NULL,
  `sd_users_id` INT NOT NULL,
  `f_id` INT NOT NULL,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sd_likes_sd_users1_idx` (`sd_users_id` ASC),
  CONSTRAINT `fk_sd_likes_sd_users1`
    FOREIGN KEY (`sd_users_id`)
    REFERENCES `rest`.`sd_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_user_boycott_signs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_user_boycott_signs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sd_userprofiles_id` INT NOT NULL,
  `sd_boycotts_id` INT NOT NULL,
  `money_spend` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `sd_userprofiles_id`, `sd_boycotts_id`),
  INDEX `fk_sd_user_boycott_signs_sd_userprofiles1_idx` (`sd_userprofiles_id` ASC),
  INDEX `fk_sd_user_boycott_signs_sd_boycotts1_idx` (`sd_boycotts_id` ASC),
  CONSTRAINT `fk_sd_user_boycott_signs_sd_userprofiles1`
    FOREIGN KEY (`sd_userprofiles_id`)
    REFERENCES `rest`.`sd_userprofiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_user_boycott_signs_sd_boycotts1`
    FOREIGN KEY (`sd_boycotts_id`)
    REFERENCES `rest`.`sd_boycotts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_user_boycott_creates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_user_boycott_creates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sd_userprofiles_id` INT NOT NULL,
  `sd_boycotts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sd_userprofiles_id`, `sd_boycotts_id`),
  INDEX `fk_sd_user_boycott_creates_sd_userprofiles1_idx` (`sd_userprofiles_id` ASC),
  INDEX `fk_sd_user_boycott_creates_sd_boycotts1_idx` (`sd_boycotts_id` ASC),
  CONSTRAINT `fk_sd_user_boycott_creates_sd_userprofiles1`
    FOREIGN KEY (`sd_userprofiles_id`)
    REFERENCES `rest`.`sd_userprofiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_user_boycott_creates_sd_boycotts1`
    FOREIGN KEY (`sd_boycotts_id`)
    REFERENCES `rest`.`sd_boycotts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_countries_has_sd_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_countries_has_sd_companies` (
  `sd_countries_id` INT NOT NULL,
  `sd_companies_id` INT NOT NULL,
  PRIMARY KEY (`sd_countries_id`, `sd_companies_id`),
  INDEX `fk_sd_countries_has_sd_companies_sd_companies1_idx` (`sd_companies_id` ASC),
  INDEX `fk_sd_countries_has_sd_companies_sd_countries1_idx` (`sd_countries_id` ASC),
  CONSTRAINT `fk_sd_countries_has_sd_companies_sd_countries1`
    FOREIGN KEY (`sd_countries_id`)
    REFERENCES `rest`.`sd_countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_countries_has_sd_companies_sd_companies1`
    FOREIGN KEY (`sd_companies_id`)
    REFERENCES `rest`.`sd_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_countries_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_countries_has_sd_tags` (
  `sd_countries_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_countries_id`, `sd_tags_id`),
  INDEX `fk_sd_countries_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_countries_has_sd_tags_sd_countries1_idx` (`sd_countries_id` ASC),
  CONSTRAINT `fk_sd_countries_has_sd_tags_sd_countries1`
    FOREIGN KEY (`sd_countries_id`)
    REFERENCES `rest`.`sd_countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_countries_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_companies_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_companies_has_sd_tags` (
  `sd_companies_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_companies_id`, `sd_tags_id`),
  INDEX `fk_sd_companies_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_companies_has_sd_tags_sd_companies1_idx` (`sd_companies_id` ASC),
  CONSTRAINT `fk_sd_companies_has_sd_tags_sd_companies1`
    FOREIGN KEY (`sd_companies_id`)
    REFERENCES `rest`.`sd_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_companies_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rest`.`sd_products_has_sd_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rest`.`sd_products_has_sd_tags` (
  `sd_products_id` INT NOT NULL,
  `sd_tags_id` INT NOT NULL,
  PRIMARY KEY (`sd_products_id`, `sd_tags_id`),
  INDEX `fk_sd_products_has_sd_tags_sd_tags1_idx` (`sd_tags_id` ASC),
  INDEX `fk_sd_products_has_sd_tags_sd_products1_idx` (`sd_products_id` ASC),
  CONSTRAINT `fk_sd_products_has_sd_tags_sd_products1`
    FOREIGN KEY (`sd_products_id`)
    REFERENCES `rest`.`sd_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sd_products_has_sd_tags_sd_tags1`
    FOREIGN KEY (`sd_tags_id`)
    REFERENCES `rest`.`sd_tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
